import BackToTop from './components/BackToTop'
import NavBar from './components/NavBar'
import NavMobile from './components/NavBarMobile'

import Footer from './components/footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lavanderia Mundial',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">

      <body id='inicio' className={inter.className}>
        <BackToTop />
        <NavBar />
        <NavMobile/>
        {children}
        <Footer />
      </body>

    </html>
  )
}


